export const configData = {
  category_heads: [
    "Kitchen",
    "Icing",
    "Dry Bakery",
    "Beverages",
    "Toppings",
    "Extra",
    "Expenses",
    "Disposable",
  ],
  delivery_heads: ["-", "Counter Sale", "On Table", "PickUp", "Home Delivery"],
  return_reason_heads: [
    "-",
    "Wrong Entry",
    "Complaint",
    "Spoilage",
    "Customer Refuse",
  ],
  tax_heads: {
    0: "No Tax",
    5: "5% (GST)",
    12: "12% (GST)",
    18: "18% (GST)",
    28: "28% (GST)",
  },
  tax_heads_purchase: {
    0: "0%",
    5: "5%",
    12: "12%",
    18: "18%",
    28: "28%",
  },
  order_delivery_status: [
    "In Process/KOT",
    "Ready To Pick",
    "On The Way",
    "Delivered",
  ],
};
