export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_CART_QTY = "SET_CART_QTY";

export const SET_OUTLET_LIST = "SET_OUTLET_LIST";
export const SET_DELIVERY_LIST = "SET_DELIVERY_LIST";

export const SET_SELECTED_OUTLET_ID = "SET_SELECTED_OUTLET_ID";
export const SET_SELECTED_OUTLET_DATA = "SET_SELECTED_OUTLET_DATA";

export const SET_PRODUCT_NOTE = "SET_PRODUCT_NOTE";
export const SET_COMPLEMENTARY_NOTE = "SET_COMPLEMENTARY_NOTE";

export const SET_TOPPING_URNO = "SET_TOPPING_URNO";
export const SET_IS_PARCEL = "SET_IS_PARCEL";
export const UPDATE_CUSTOMIZED = 'UPDATE_CUSTOMIZED';
