export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_CART_QTY = "SET_CART_QTY";

export const SET_OUTLET_LIST = "SET_OUTLET_LIST";
// export const SET_OUTLET_LIST
export const SET_DELIVERY_LIST = "SET_DELIVERY_LIST";

export const SET_SELECTED_OUTLET_ID = "SET_SELECTED_OUTLET_ID";
export const SET_SELECTED_OUTLET_DATA = "SET_SELECTED_OUTLET_DATA";

export const SET_PRODUCT_NOTE = "SET_PRODUCT_NOTE";
export const SET_COMPLEMENTARY_NOTE = "SET_COMPLEMENTARY_NOTE";

export const SET_TOPPING_URNO = "SET_TOPPING_URNO";
export const SET_IS_PARCEL = "SET_IS_PARCEL";
export const UPDATE_CUSTOMIZED = "UPDATE_CUSTOMIZED";

export const SET_USER="SET_USER";
export const LOGOUT_USER="LOGOUT_USER";

export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const SELECT_DELIVERY = "SELECT_DELIVERY";

export const SET_SELECTED_CUSTOMER = "SET_SELECTED_CUSTOMER";
export const CLEAR_SELECTED_CUSTOMER = "CLEAR_SELECTED_CUSTOMER";
export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS";
