export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_CART_QTY = "SET_CART_QTY";
export const SET_NEW_CART = "SET_NEW_CART";

export const SET_OUTLET_LIST = "SET_OUTLET_LIST";
// export const SET_OUTLET_LIST
export const SET_DELIVERY_LIST = "SET_DELIVERY_LIST";

export const SET_SELECTED_OUTLET_ID = "SET_SELECTED_OUTLET_ID";
export const SET_SELECTED_OUTLET_DATA = "SET_SELECTED_OUTLET_DATA";

export const SET_PRODUCT_NOTE = "SET_PRODUCT_NOTE";
export const SET_COMPLEMENTARY_NOTE = "SET_COMPLEMENTARY_NOTE";

export const SET_TOPPING_URNO = "SET_TOPPING_URNO";
export const SET_IS_PARCEL = "SET_IS_PARCEL";
export const UPDATE_CUSTOMIZED = "UPDATE_CUSTOMIZED";

export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const SELECT_DELIVERY = "SELECT_DELIVERY";

export const SET_SELECTED_CUSTOMER = "SET_SELECTED_CUSTOMER";
export const CLEAR_SELECTED_CUSTOMER = "CLEAR_SELECTED_CUSTOMER";
export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS";

export const SET_SUBMITTED_PICKUP_DATE_TIME = "SET_SUBMITTED_PICKUP_DATE_TIME";

export const SET_RECENT_BOOKINGS = "SET_RECENT_BOOKINGS";

export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";

export const SET_INPUT_FIELD_FOCUS = "SET_INPUT_FIELD_FOCUS";
export const SET_INPUT_FIELD_BLUR = "SET_INPUT_FIELD_BLUR";
export const SET_CUSTOMER_ACCOUNT_JSON = "SET_CUSTOMER_ACCOUNT_JSON";
export const SET_CART_SUM_UP = "SET_CART_SUM_UP";
export const SET_SELECTED_CUSTOMER_JSON = "SET_SELECTED_CUSTOMER_JSON";
export const UPDATE_TOTAL_CASH = "UPDATE_TOTAL_CASH";
export const UPDATE_PAY_MODE_TOTALS = "UPDATE_PAY_MODE_TOTALS";
export const GET_SAVE_SALE_DATA = "GET_SAVE_SALE_DATA";
export const SET_SELECTED_TABLE_VALUE = "SET_SELECTED_TABLE_VALUE";
export const SUBMIT_DELIVERY_DATA = "SUBMIT_DELIVERY_DATA";


